# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Ingredient.destroy_all

Ingredient.create(
  [
    { name: "Big Hearty Radish", base_hearts_recovered:	4},
    { name: "Hearty Salmon", base_hearts_recovered:	4},
    { name: "Hearty Durian", base_hearts_recovered:	3},
    { name: "Big Hearty Truffle", base_hearts_recovered:	3},
    { name: "Hearty Blueshell Snail", base_hearts_recovered:	3},
    { name: "Hearty Radish", base_hearts_recovered:	2.5},
    { name: "Hearty Truffle", base_hearts_recovered:	2},
    { name: "Hearty Bass", base_hearts_recovered:	2},
    { name: "Hearty Lizard", base_hearts_recovered:	0},
    { name: "Fairy", base_hearts_recovered:	5},
    { name: "Raw Gourmet Meat", base_hearts_recovered:	3},
    { name: "Raw Whole Bird", base_hearts_recovered:	3},
    { name: "Raw Prime Meat", base_hearts_recovered:	1.5},
    { name: "Raw Bird Thigh", base_hearts_recovered:	1.5},
    { name: "Palm Fruit", base_hearts_recovered:	1},
    { name: "Hyrule Herb", base_hearts_recovered:	1},
    { name: "Raw Meat", base_hearts_recovered:	1},
    { name: "Raw Bird Drumstick", base_hearts_recovered:	1},
    { name: "Hylian Rice", base_hearts_recovered:	1},
    { name: "Bird Egg", base_hearts_recovered:	1},
    { name: "Tabantha Wheat", base_hearts_recovered:	1},
    { name: "Hyrule Bass", base_hearts_recovered:	1},
    { name: "Sanke Carp", base_hearts_recovered:	1},
    { name: "Fresh Milk", base_hearts_recovered:	0.5},
    { name: "Apple", base_hearts_recovered:	0.5},
    { name: "Wildberry", base_hearts_recovered:	0.5},
    { name: "Hylian Shroom", base_hearts_recovered:	0.5},
    { name: "Acorn", base_hearts_recovered:	0.25},
    { name: "Chickaloo Tree Nut", base_hearts_recovered:	0.25},
    { name: "Tireless Frog", base_hearts_recovered:	4},
    { name: "Endura Carrot", base_hearts_recovered:	2},
    { name: "Endura Shroom", base_hearts_recovered:	1},
    { name: "Smotherwing Butterfly", base_hearts_recovered:	0},
    { name: "Fireproof Lizard", base_hearts_recovered:	0},
    { name: "Chillfin Trout", base_hearts_recovered:	1},
    { name: "Chillshroom", base_hearts_recovered:	0.5},
    { name: "Hydromelon", base_hearts_recovered:	0.5},
    { name: "Cool Safflina", base_hearts_recovered:	0},
    { name: "Winterwing Butterfly", base_hearts_recovered:	0},
    { name: "Cold Darner", base_hearts_recovered:	0},
    { name: "Sizzlefin Trout", base_hearts_recovered:	1},
    { name: "Spicy Pepper", base_hearts_recovered:	0.5},
    { name: "Sunshroom", base_hearts_recovered:	0.5},
    { name: "Summerwing Butterfly", base_hearts_recovered:	0},
    { name: "Warm Darner", base_hearts_recovered:	0},
    { name: "Voltfin Trout", base_hearts_recovered:	1},
    { name: "Zapshroom", base_hearts_recovered:	0.5},
    { name: "Voltfruit", base_hearts_recovered:	0.5},
    { name: "Electric Safflina", base_hearts_recovered:	0},
    { name: "Thunderwing Butterfly", base_hearts_recovered:	0},
    { name: "Electric Darner", base_hearts_recovered:	0},
    { name: "Fleet-Lotus Seeds", base_hearts_recovered:	0.5},
    { name: "Rushroom", base_hearts_recovered:	0.5},
    { name: "Swift Carrot", base_hearts_recovered:	0.5},
    { name: "Hot-Footed Frog", base_hearts_recovered:	0},
    { name: "Hightail Lizard", base_hearts_recovered:	0},
    { name: "Silent Princess", base_hearts_recovered:	2},
    { name: "Stealthfin Trout", base_hearts_recovered:	1},
    { name: "Sneaky River Snail", base_hearts_recovered:	1},
    { name: "Silent Shroom", base_hearts_recovered:	0.5},
    { name: "Swift Violet", base_hearts_recovered:	0},
    { name: "Blue Nightshade", base_hearts_recovered:	0},
    { name: "Sunset Firefly", base_hearts_recovered:	0},
    { name: "Mighty Carp", base_hearts_recovered:	1},
    { name: "Mighty Porgy", base_hearts_recovered:	1},
    { name: "Razorclaw Crab", base_hearts_recovered:	1},
    { name: "Mighty Bananas", base_hearts_recovered:	0.5},
    { name: "Razorshroom", base_hearts_recovered:	0.5},
    { name: "Bladed Rhino Beetle", base_hearts_recovered:	0},
    { name: "Mighty Thistle", base_hearts_recovered:	0}
  ]
)
